CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) UNIQUE NOT NULL,
 phone VARCHAR(20) UNIQUE NULL,
 student_id VARCHAR(40) UNIQUE NULL,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'user',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INT NOT NULL,
 item_name VARCHAR(150) NOT NULL,
 category VARCHAR(80) NOT NULL,
 description TEXT NOT NULL,
 location VARCHAR(200) NOT NULL,
 event_date DATE NOT NULL,
 image VARCHAR(255),
 status VARCHAR(32) NOT NULL,
 icon VARCHAR(80) DEFAULT 'fa-box',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 brand VARCHAR(100) DEFAULT NULL,
 color VARCHAR(60) DEFAULT NULL,
 is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
 qr_token CHAR(36) DEFAULT NULL UNIQUE,
 event_time TIME DEFAULT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS claims (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 item_id INT NOT NULL,
 user_id INT NOT NULL,
 proof TEXT NOT NULL,
 proof_image VARCHAR(255) DEFAULT NULL,
 proof_file VARCHAR(255) DEFAULT NULL,
 status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
 handover_at DATETIME DEFAULT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INT NOT NULL,
 message VARCHAR(255) NOT NULL,
 is_read BOOLEAN DEFAULT FALSE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 actor_id INT NULL,
 action VARCHAR(80) NOT NULL,
 entity_type VARCHAR(40) NOT NULL,
 entity_id INT NULL,
 details TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS handover_receipts (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 item_id INT NOT NULL UNIQUE,
 claim_id INT NOT NULL,
 receiver_id INT NOT NULL,
 receiver_name VARCHAR(100) NOT NULL,
 receiver_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
 authorized_staff_id INT NOT NULL,
 authorized_staff_name VARCHAR(100) NOT NULL,
 confirmed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
 FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE CASCADE,
 FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (authorized_staff_id) REFERENCES users(id) ON DELETE CASCADE
);

-- After registering your first account, promote it to administrator in the Staff panel.
